create or replace view SF_DEVOPS_DEV_DB.BRONZE.VW_CUSTOMER(
	SALE_ID,
	PRODUCT_ID,
	SALE_DATE,
	QUANTITY,
	UNIT_PRICE,
	STORE_ID,
	_INSERTED_TIMESTAMP
) as SELECT * FROM SF_DEVOPS_DEV_DB.BRONZE.CUSTOMER_RAW_BRONZE;;

